// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEQ4AhM3abDDalZtbWd9Co9w7SVIVFR9Y',
    appId: '1:629967934317:web:85fbcceb0f5b7a3222c064',
    messagingSenderId: '629967934317',
    projectId: 'profirecom-9b476',
    authDomain: 'profirecom-9b476.firebaseapp.com',
    storageBucket: 'profirecom-9b476.appspot.com',
    measurementId: 'G-W40TTXHXLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHRa773V2GcoQeMGq-5P6Vw-nhizgMVWE',
    appId: '1:629967934317:android:64faaac6f2eee09e22c064',
    messagingSenderId: '629967934317',
    projectId: 'profirecom-9b476',
    storageBucket: 'profirecom-9b476.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKgE6c2BOA4cy72w_XYclwpeS5i8uKY-U',
    appId: '1:629967934317:ios:e148149b1be5326f22c064',
    messagingSenderId: '629967934317',
    projectId: 'profirecom-9b476',
    storageBucket: 'profirecom-9b476.appspot.com',
    iosClientId: '629967934317-l3torb2j89r2t6vj10c80dssbqk8rchi.apps.googleusercontent.com',
    iosBundleId: 'com.example.profirecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKgE6c2BOA4cy72w_XYclwpeS5i8uKY-U',
    appId: '1:629967934317:ios:e148149b1be5326f22c064',
    messagingSenderId: '629967934317',
    projectId: 'profirecom-9b476',
    storageBucket: 'profirecom-9b476.appspot.com',
    iosClientId: '629967934317-l3torb2j89r2t6vj10c80dssbqk8rchi.apps.googleusercontent.com',
    iosBundleId: 'com.example.profirecom',
  );
}
